### ISSUE TITLE
Error: Cannot find module 'is-property'

### ISSUE THREAD

**Issue by karenpeng** [mafintosh/csv-parser#33]
when running csv-parser, it misses a module
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'is-property'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/.../node_modules/csv-parser/node_modules/generate-object-property/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by mafintosh** [comment]
Hmm thats sounds like a weird npm issue. I've heard other people have the same problem. What version of node/npm are you running?

**Comment by karenpeng** [comment]
node v0.12.7
npm 2.11.3

**Comment by karenpeng** [comment]
Ah, I upgraded node, it still has the same error.
But after upgraded npm, it works fine!

**Comment by mafintosh** [comment]
Good to hear :)
