### ISSUE TITLE
"Cannot find module './package'"

### ISSUE THREAD

**Issue by tjconcept** [mafintosh/csv-parser#98]
* Operating System: macOS 10.13.6
* Node Version: 10.11.0 (tested 10.8.0 as well)
* NPM Version: 6.4.1
* csv-parser Version: 2.0.0

### Expected Behavior

```
$ npm i -g csv-parser
$ csv-parser -v
2.0.0
```

### Actual Behavior

```
$ npm i -g csv-parser
$ csv-parser -v
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './package'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/tj/.npm-config/lib/node_modules/csv-parser/bin/csv-parser:30:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

### How Do We Reproduce?

```
$ npm i -g csv-parser
$ csv-parser -v
```

**Comment by shellscape** [comment]
Thanks for the report!
