### ISSUE TITLE
"this.mapHeaders is not a function"

### ISSUE THREAD

**Issue by tjconcept** [mafintosh/csv-parser#99]
* Operating System: macOS 10.13.6
* Node Version: 10.11.0
* NPM Version: 6.4.1
* csv-parser Version: 2.0.0

### Expected Behavior

```
$ echo "a
> 1" | csv-parser
{"a": "1"}
```

### Actual Behavior

```
$ echo "a
> 1" | csv-parser
/Users/tj/.npm-config/lib/node_modules/csv-parser/index.js:70
        const newHeader = this.mapHeaders({ header, index })
                               ^

TypeError: this.mapHeaders is not a function
    at headers.forEach (/Users/tj/.npm-config/lib/node_modules/csv-parser/index.js:70:32)
    at Array.forEach (<anonymous>)
    at CsvParser._compile (/Users/tj/.npm-config/lib/node_modules/csv-parser/index.js:69:20)
    at CsvParser._online (/Users/tj/.npm-config/lib/node_modules/csv-parser/index.js:181:12)
    at CsvParser._transform (/Users/tj/.npm-config/lib/node_modules/csv-parser/index.js:242:16)
    at CsvParser.Transform._read (_stream_transform.js:190:10)
    at CsvParser.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at CsvParser.Writable.write (_stream_writable.js:294:11)
```

### How Do We Reproduce?

```
$ echo "a
> 1" | csv-parser
```

**Comment by shellscape** [comment]
Not sure what scenario would cause this. Our tests don't reflect that, and I'm unable to reproduce using your example. Line 29 in the v2.0.0 tag source (which you're running) sets the options and asserts that mapHeaders cannot be undefined https://github.com/mafintosh/csv-parser/blob/97edb38c970824039766369058df47d81a445f28/index.js#L26 which is then set on line 37 to the instance https://github.com/mafintosh/csv-parser/blob/97edb38c970824039766369058df47d81a445f28/index.js#L37, and line 69 is using an arrow function https://github.com/mafintosh/csv-parser/blob/97edb38c970824039766369058df47d81a445f28/index.js#L69 so`this` is from the same scope as the previous line, on which `this.headers` exists.

Probably something you're going to have to investigate on your end and submit a patch or PR for.

**Comment by tjconcept** [comment]
What? It's right here: https://github.com/mafintosh/csv-parser/blob/2c95c35a758ab40ac1b88daac08520aa7b65fdaf/bin/csv-parser#L73

**Comment by tjconcept** [comment]
I don't have a fix. I have no idea what that code does.

How could yours work? I suppose that's the key to the bug.

**Comment by dimfeld** [comment]
It looks like `bin/csv-parser` wasn't updated for the breaking changes in version 2.

**Comment by shellscape** [comment]
Happy to merge and publish a PR to fix. Just don't have the time to triage for another week or so.

**Comment by dimfeld** [comment]
The root of the problem appears to be where the defaults are merged with the passed-in options. https://github.com/mafintosh/csv-parser/blob/2c95c35a758ab40ac1b88daac08520aa7b65fdaf/index.js#L29 where the default and options merge used to be a more manual process performed in a way that would not treat falsy values for the `map*` functions as valid arguments. (Below code is from the v1.12.1 tag) https://github.com/mafintosh/csv-parser/blob/d8791d38bc79a2239ede843bc352bf78ba92eebf/index.js#L32

The most obvious fix to me is to just revert back to the old option-parsing code, maybe just for the map functions. If that sounds ok to you, I can probably submit a PR some time this week. `bin/csv-parser` also needs its mapHeaders arguments updated.

**Comment by tjconcept** [comment]
I agree with that analysis, but that doesn't explain why @shellscape is not able to reproduce it. I think that should be debugged first.

**Comment by shellscape** [comment]
(On a plane right now and the wifi is miraculously working)

It might be a sticky global bin. My first step in every issue is to try and reproduce locally. If it's unreproducible for me, but reproducible for a bunch of others, then it's probably a wonk on my end. I wouldn't give my lack of reproduction much credence until I've got the time to investigate.

I wouldn't recommend a reversion as a fix, but rather trying to get the new style to party correctly with the breaking changes in the major.
